services:
  sync:
    image: frappe/erpnext:v15.107.0
    entrypoint:
      - bash
      - -c
    command:
      - >
        cd /home/frappe/volumes;
        ./copy_files.sh --from-host;
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
      - apps:/home/frappe/frappe-bench/apps
      - ./volumes:/home/frappe/volumes:ro

  backup:
    image: frappe/erpnext:v15.107.0
    entrypoint:
      - bash
      - -c
    command:
      - >
        cd /home/frappe/volumes;
        ./copy_files.sh;
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
      - apps:/home/frappe/frappe-bench/apps
      - ./volumes:/home/frappe/volumes:rw

volumes:
  db-data:
  apps:
  sites:
  logs: